### ISSUE TITLE
Visualizzare mappa e creare metodo per maschera di bit

### ISSUE THREAD

**Issue by tudormardare** [tudormardare/Jump#7]
std::vector<bool> createCollisionMask(const sf::Sprite& sprite) {
    sf::Image image = sprite.getTexture()->copyToImage();
    std::vector<bool> mask(image.getSize().x * image.getSize().y, false);

    for (unsigned int x = 0; x < image.getSize().x; x++) {
        for (unsigned int y = 0; y < image.getSize().y; y++) {
            mask[x + y * image.getSize().x] = image.getPixel(x, y).a != 0;
        }
    }

    return mask;
}

**Comment by denisjaupi** [comment]
2468e47f99ca37a601b80e4c80e3a628b1cf5863
